theme: jekyll-theme-minimal
title: RAFAŁ LORENZ
description: SOFTWARE ARCHITECT
show_downloads: false
google_analytics: UA-42622274-2
cv_url: http://stackoverflow.com/cv/vardius
linkedin_url: https://www.linkedin.com/in/vardius
stack_overflow_url: http://stackoverflow.com/users/2160958/vardius
facebook_url: https://www.facebook.com/vardius
